services:

  db:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: databasehaip
      MYSQL_DATABASE: haip
    restart: always

  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - 3001:3001
    env_file:
      - ./server/src/.env
    depends_on:
      - db

  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - 3000:3000