services:
  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    volumes:
      - ./server:/app
    ports:
      - 3001:3001
    env_file:
      - ./server/src/.env

  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - ./client:/app
    ports:
      - 3000:3000