CREATE TABLE users (
    USER_ID VARCHAR(255) PRIMARY KEY
);

CREATE TABLE playlists (
    USER_ID VARCHAR(255),
    PLAYLIST_ID VARCHAR(255) PRIMARY KEY,
    FOREIGN KEY (USER_ID) REFERENCES haip.users(USER_ID)
);